import type { RecordIndexConfig } from '@/src/components/admin/RecordIndexPage';

function createOptions(labels: string[]) {
  return [{ value: 'all', label: 'All' }, ...labels.map((label) => ({ value: label, label }))];
}

export const WORK_ORDERS_CONFIG: RecordIndexConfig = {
  eyebrow: 'Operations',
  title: 'Work Orders',
  description: 'Field work records, active dispatch queue, and crew readiness in one view.',
  searchPlaceholder: 'Search work orders, clients, crews, or zones',
  filterLabel: 'Stage',
  emptyMessage: 'No work orders match this search/filter combination.',
  filterOptions: createOptions(['scheduled', 'active', 'qa']),
  gridClassName: 'grid gap-4 md:grid-cols-2 xl:grid-cols-3',
  records: [
    {
      id: 'wo-1048',
      name: 'WO-1048 • Northside HVAC Retrofit',
      subtitle: 'Commercial install package with aftercare call.',
      category: 'active',
      metric: 'Crew A on-site',
      accent: '#0f766e',
      badge: { label: 'active', variant: 'success' },
      tags: ['Commercial', 'Priority'],
      meta: [
        { label: 'Client', value: 'Northside Plaza' },
        { label: 'ETA', value: 'Today 2:30 PM' },
      ],
    },
    {
      id: 'wo-1052',
      name: 'WO-1052 • Summit Leak Investigation',
      subtitle: 'Diagnostics + temporary patching visit.',
      category: 'scheduled',
      metric: '2 techs assigned',
      accent: '#1d4ed8',
      badge: { label: 'scheduled', variant: 'info' },
      tags: ['Residential', 'Leak'],
      meta: [
        { label: 'Client', value: 'Summit Estates' },
        { label: 'Window', value: 'Fri 9:00–11:00' },
      ],
    },
    {
      id: 'wo-1057',
      name: 'WO-1057 • Harbor QA Walkthrough',
      subtitle: 'Closeout checks before final invoice release.',
      category: 'qa',
      metric: 'Checklist 84%',
      accent: '#b45309',
      badge: { label: 'qa', variant: 'warning' },
      tags: ['Closeout', 'Inspection'],
      meta: [
        { label: 'Client', value: 'Harbor Logistics' },
        { label: 'Owner', value: 'Nina T.' },
      ],
    },
    {
      id: 'wo-1063',
      name: 'WO-1063 • Greenline Duct Balance',
      subtitle: 'Airflow balancing and comfort calibration.',
      category: 'scheduled',
      metric: '3 zones pending',
      accent: '#7c3aed',
      badge: { label: 'scheduled', variant: 'outline' },
      tags: ['Tune-up', 'Calibration'],
      meta: [
        { label: 'Client', value: 'Greenline HQ' },
        { label: 'Start', value: 'Mon 8:00 AM' },
      ],
    },
  ],
};

export const ESTIMATES_CONFIG: RecordIndexConfig = {
  eyebrow: 'Operations',
  title: 'Estimates',
  description: 'Open quotes, revision flow, and conversion readiness.',
  searchPlaceholder: 'Search estimate IDs, client names, or service scope',
  filterLabel: 'Status',
  emptyMessage: 'No estimates found for this filter.',
  filterOptions: createOptions(['draft', 'sent', 'approved']),
  gridClassName: 'grid gap-4 md:grid-cols-2 xl:grid-cols-3',
  records: [
    {
      id: 'est-222',
      name: 'EST-222 • Main Street Rewire',
      subtitle: 'Panel upgrade + surge protection package.',
      category: 'sent',
      metric: '$18,400',
      accent: '#0f766e',
      badge: { label: 'sent', variant: 'info' },
      tags: ['Electrical', 'Commercial'],
      meta: [
        { label: 'Client', value: 'Main Street Dental' },
        { label: 'Sent', value: 'May 24' },
      ],
    },
    {
      id: 'est-227',
      name: 'EST-227 • Oakridge Comfort Plan',
      subtitle: 'Seasonal maintenance and monitoring bundle.',
      category: 'approved',
      metric: '$6,920',
      accent: '#1d4ed8',
      badge: { label: 'approved', variant: 'success' },
      tags: ['Maintenance', 'Recurring'],
      meta: [
        { label: 'Client', value: 'Oakridge HOA' },
        { label: 'Close date', value: 'May 27' },
      ],
    },
    {
      id: 'est-231',
      name: 'EST-231 • Harbor Cooling Retrofit',
      subtitle: 'Efficiency redesign for second-floor office wing.',
      category: 'draft',
      metric: '$24,300',
      accent: '#7c2d12',
      badge: { label: 'draft', variant: 'outline' },
      tags: ['Retrofit', 'HVAC'],
      meta: [
        { label: 'Client', value: 'Harbor Group' },
        { label: 'Owner', value: 'Luis M.' },
      ],
    },
  ],
};

export const CATALOG_CONFIG: RecordIndexConfig = {
  eyebrow: 'Operations',
  title: 'Catalog',
  description: 'Service and inventory records used by estimates and work orders.',
  searchPlaceholder: 'Search SKUs, materials, and catalog groups',
  filterLabel: 'Catalog Group',
  emptyMessage: 'No catalog records match your search.',
  filterOptions: createOptions(['materials', 'equipment', 'service']),
  gridClassName: 'grid gap-4 md:grid-cols-2 xl:grid-cols-3',
  records: [
    {
      id: 'cat-1',
      name: 'MAT-302 • Copper Coil 3/4"',
      subtitle: 'Primary install stock with tracked reorder thresholds.',
      category: 'materials',
      metric: '42 units',
      accent: '#0f766e',
      badge: { label: 'materials', variant: 'secondary' },
      tags: ['Stocked', 'Install'],
      meta: [
        { label: 'Cost', value: '$84.00' },
        { label: 'Vendor', value: 'Allied Supply' },
      ],
    },
    {
      id: 'cat-2',
      name: 'EQ-810 • Smart Control Panel',
      subtitle: 'Networked controller package with remote diagnostics.',
      category: 'equipment',
      metric: '9 in stock',
      accent: '#1d4ed8',
      badge: { label: 'equipment', variant: 'info' },
      tags: ['Controller', 'Premium'],
      meta: [
        { label: 'Cost', value: '$1,120.00' },
        { label: 'Lead time', value: '5 days' },
      ],
    },
    {
      id: 'cat-3',
      name: 'SRV-115 • Duct Sanitization',
      subtitle: 'Add-on service for remediation and post-project care.',
      category: 'service',
      metric: '$440 list',
      accent: '#7c3aed',
      badge: { label: 'service', variant: 'outline' },
      tags: ['Add-on', 'High margin'],
      meta: [
        { label: 'Duration', value: '2.5 hours' },
        { label: 'Bundle', value: 'Comfort+ Plan' },
      ],
    },
  ],
};

export const OFFERINGS_CONFIG: RecordIndexConfig = {
  eyebrow: 'Operations',
  title: 'Offerings',
  description: 'Packaged services and pricing bundles used by sales and fulfillment.',
  searchPlaceholder: 'Search offerings, bundle names, or tiers',
  filterLabel: 'Tier',
  emptyMessage: 'No offerings are visible for this filter.',
  filterOptions: createOptions(['core', 'premium', 'enterprise']),
  gridClassName: 'grid gap-4 md:grid-cols-2 xl:grid-cols-3',
  records: [
    {
      id: 'off-1',
      name: 'Comfort Baseline',
      subtitle: 'Quarterly inspections and priority scheduling.',
      category: 'core',
      metric: '$159/mo',
      accent: '#0f766e',
      badge: { label: 'core', variant: 'success' },
      tags: ['Recurring', 'Residential'],
      meta: [
        { label: 'Renewal', value: '84%' },
        { label: 'Subscribers', value: '312' },
      ],
    },
    {
      id: 'off-2',
      name: 'Facility Shield',
      subtitle: 'Commercial preventive care with response SLAs.',
      category: 'enterprise',
      metric: '$2,900/qtr',
      accent: '#1d4ed8',
      badge: { label: 'enterprise', variant: 'info' },
      tags: ['Commercial', 'SLA'],
      meta: [
        { label: 'Accounts', value: '18' },
        { label: 'SLA', value: '4hr response' },
      ],
    },
    {
      id: 'off-3',
      name: 'Energy Upgrade Sprint',
      subtitle: 'High-efficiency retrofit package with reporting.',
      category: 'premium',
      metric: '$12,400 avg',
      accent: '#7c2d12',
      badge: { label: 'premium', variant: 'warning' },
      tags: ['Retrofit', 'Analytics'],
      meta: [
        { label: 'Margin', value: '38%' },
        { label: 'Cycle', value: '28 days' },
      ],
    },
  ],
};

export const ORGANIZATIONS_CONFIG: RecordIndexConfig = {
  eyebrow: 'Customer Relations',
  title: 'Organizations',
  description: 'Account-level CRM records with ownership and health indicators.',
  searchPlaceholder: 'Search organizations, owners, and account segments',
  filterLabel: 'Segment',
  emptyMessage: 'No organizations match this filter.',
  filterOptions: createOptions(['enterprise', 'mid-market', 'local']),
  gridClassName: 'grid gap-4 md:grid-cols-2 xl:grid-cols-3',
  records: [
    {
      id: 'org-1',
      name: 'Northside Plaza',
      subtitle: 'Multi-site commercial property group.',
      category: 'enterprise',
      metric: 'Health 91',
      accent: '#0f766e',
      badge: { label: 'active', variant: 'success' },
      tags: ['Commercial', 'Multi-site'],
      meta: [
        { label: 'Owner', value: 'Janelle R.' },
        { label: 'Open work orders', value: '4' },
      ],
    },
    {
      id: 'org-2',
      name: 'Oakridge HOA',
      subtitle: 'Seasonal maintenance and emergency response account.',
      category: 'mid-market',
      metric: 'Health 84',
      accent: '#1d4ed8',
      badge: { label: 'retained', variant: 'info' },
      tags: ['HOA', 'Recurring'],
      meta: [
        { label: 'Owner', value: 'Paul V.' },
        { label: 'Renewal', value: 'Aug 14' },
      ],
    },
    {
      id: 'org-3',
      name: 'Summit Estates',
      subtitle: 'Local residential builder partner.',
      category: 'local',
      metric: 'Health 76',
      accent: '#7c3aed',
      badge: { label: 'watchlist', variant: 'warning' },
      tags: ['Builder', 'Referral'],
      meta: [
        { label: 'Owner', value: 'Mila D.' },
        { label: 'Recent activity', value: '2 days ago' },
      ],
    },
  ],
};

export const CONTACTS_CONFIG: RecordIndexConfig = {
  eyebrow: 'Customer Relations',
  title: 'Contacts',
  description: 'Primary contact records with communication channel and assignment visibility.',
  searchPlaceholder: 'Search contact names, roles, or organizations',
  filterLabel: 'Role',
  emptyMessage: 'No contacts found for this query.',
  filterOptions: createOptions(['operations', 'finance', 'executive']),
  gridClassName: 'grid gap-4 md:grid-cols-2 xl:grid-cols-3',
  records: [
    {
      id: 'con-1',
      name: 'Avery Kim',
      subtitle: 'Facilities lead at Northside Plaza.',
      category: 'operations',
      metric: 'Last touch: Today',
      accent: '#0f766e',
      badge: { label: 'primary', variant: 'success' },
      tags: ['SMS', 'Decision maker'],
      meta: [
        { label: 'Org', value: 'Northside Plaza' },
        { label: 'Owner', value: 'Nina T.' },
      ],
    },
    {
      id: 'con-2',
      name: 'Jordan Pike',
      subtitle: 'Controller handling invoice approvals.',
      category: 'finance',
      metric: 'Response: 3h avg',
      accent: '#1d4ed8',
      badge: { label: 'finance', variant: 'info' },
      tags: ['Invoices', 'ACH'],
      meta: [
        { label: 'Org', value: 'Harbor Group' },
        { label: 'Email', value: 'jpike@harbor.co' },
      ],
    },
    {
      id: 'con-3',
      name: 'Mara Quinn',
      subtitle: 'Regional VP for project escalations.',
      category: 'executive',
      metric: 'Escalations: 1',
      accent: '#7c2d12',
      badge: { label: 'executive', variant: 'warning' },
      tags: ['Escalation', 'VIP'],
      meta: [
        { label: 'Org', value: 'Summit Estates' },
        { label: 'Preferred', value: 'Phone' },
      ],
    },
  ],
};

export const CAMPAIGNS_CONFIG: RecordIndexConfig = {
  eyebrow: 'Marketing & Ads',
  title: 'Campaigns',
  description: 'Campaign records with budget, channel mix, and pacing snapshots.',
  searchPlaceholder: 'Search campaign names, channels, or objectives',
  filterLabel: 'Objective',
  emptyMessage: 'No campaigns match this filter.',
  filterOptions: createOptions(['awareness', 'retargeting', 'lead-gen']),
  gridClassName: 'grid gap-4 md:grid-cols-2 xl:grid-cols-3',
  records: [
    {
      id: 'cmp-1',
      name: 'Summer Comfort Push',
      subtitle: 'Cross-channel AC tune-up awareness sequence.',
      category: 'awareness',
      metric: '$9.2k spend',
      accent: '#be185d',
      badge: { label: 'live', variant: 'success' },
      tags: ['Meta', 'Search'],
      meta: [
        { label: 'CTR', value: '4.8%' },
        { label: 'Owner', value: 'Maya C.' },
      ],
    },
    {
      id: 'cmp-2',
      name: 'Dormant Lead Reboot',
      subtitle: 'Remarketing sequence for stale estimate pipeline.',
      category: 'retargeting',
      metric: '$3.6k spend',
      accent: '#1d4ed8',
      badge: { label: 'testing', variant: 'info' },
      tags: ['Email', 'Meta'],
      meta: [
        { label: 'CVR', value: '3.1%' },
        { label: 'Window', value: '14 days' },
      ],
    },
    {
      id: 'cmp-3',
      name: 'Commercial Upgrade Leads',
      subtitle: 'Intent campaign targeting facilities teams.',
      category: 'lead-gen',
      metric: '42 MQLs',
      accent: '#0f766e',
      badge: { label: 'scaled', variant: 'warning' },
      tags: ['LinkedIn', 'Search'],
      meta: [
        { label: 'CPL', value: '$118' },
        { label: 'Owner', value: 'Ryan N.' },
      ],
    },
  ],
};

export const LEADS_CONFIG: RecordIndexConfig = {
  eyebrow: 'Customer Relations',
  title: 'Leads',
  description: 'Lead records with source, owner, and immediate conversion context.',
  searchPlaceholder: 'Search leads, sources, and assigned owner',
  filterLabel: 'Stage',
  emptyMessage: 'No leads found for this filter.',
  filterOptions: createOptions(['new', 'qualified', 'proposal']),
  gridClassName: 'grid gap-4 md:grid-cols-2 xl:grid-cols-3',
  records: [
    {
      id: 'lead-1',
      name: 'Acme Corp Expansion',
      subtitle: 'Headquarters wing retrofit inquiry.',
      category: 'qualified',
      metric: '$48k potential',
      accent: '#0f766e',
      badge: { label: 'qualified', variant: 'success' },
      tags: ['Inbound', 'Commercial'],
      meta: [
        { label: 'Owner', value: 'JP' },
        { label: 'Source', value: 'Website form' },
      ],
    },
    {
      id: 'lead-2',
      name: 'Vanguard Labs',
      subtitle: 'Preventive maintenance bid request.',
      category: 'new',
      metric: 'Follow-up due',
      accent: '#1d4ed8',
      badge: { label: 'new', variant: 'info' },
      tags: ['Referral', 'B2B'],
      meta: [
        { label: 'Owner', value: 'Sarah' },
        { label: 'Source', value: 'Partner referral' },
      ],
    },
    {
      id: 'lead-3',
      name: 'Oakwell Medical',
      subtitle: 'Urgent cooling replacement proposal.',
      category: 'proposal',
      metric: '$22k pipeline',
      accent: '#7c2d12',
      badge: { label: 'proposal', variant: 'warning' },
      tags: ['Urgent', 'Healthcare'],
      meta: [
        { label: 'Owner', value: 'Nina' },
        { label: 'Source', value: 'Phone intake' },
      ],
    },
  ],
};

export const INVOICES_CONFIG: RecordIndexConfig = {
  eyebrow: 'Banking',
  title: 'Invoices',
  description: 'Invoice records with settlement stage, amount, and owner visibility.',
  searchPlaceholder: 'Search invoice IDs, clients, or payment method',
  filterLabel: 'Stage',
  emptyMessage: 'No invoices match this search/filter.',
  filterOptions: createOptions(['draft', 'sent', 'paid']),
  gridClassName: 'grid gap-4 md:grid-cols-2 xl:grid-cols-3',
  records: [
    {
      id: 'inv-1',
      name: 'INV-4401 • Northside Plaza',
      subtitle: 'Phase 2 install completion invoice.',
      category: 'sent',
      metric: '$18,400',
      accent: '#0f766e',
      badge: { label: 'sent', variant: 'info' },
      tags: ['ACH', 'Commercial'],
      meta: [
        { label: 'Due', value: 'Jun 2' },
        { label: 'Owner', value: 'Jordan P.' },
      ],
    },
    {
      id: 'inv-2',
      name: 'INV-4407 • Summit Estates',
      subtitle: 'Leak response and patch package.',
      category: 'draft',
      metric: '$3,120',
      accent: '#1d4ed8',
      badge: { label: 'draft', variant: 'outline' },
      tags: ['Residential', 'Rapid'],
      meta: [
        { label: 'Prepared', value: 'Today' },
        { label: 'Owner', value: 'Mila D.' },
      ],
    },
    {
      id: 'inv-3',
      name: 'INV-4410 • Harbor Group',
      subtitle: 'Quarterly maintenance cycle billing.',
      category: 'paid',
      metric: '$9,860',
      accent: '#7c3aed',
      badge: { label: 'paid', variant: 'success' },
      tags: ['Recurring', 'Auto-pay'],
      meta: [
        { label: 'Paid', value: 'May 27' },
        { label: 'Owner', value: 'Nina T.' },
      ],
    },
  ],
};

export const ADS_CONFIG: RecordIndexConfig = {
  eyebrow: 'Marketing & Ads',
  title: 'Ads',
  description: 'Ad creative records with channel, spend, and performance snapshot.',
  searchPlaceholder: 'Search ad names, channels, or creative type',
  filterLabel: 'Channel',
  emptyMessage: 'No ad records matched your filter.',
  filterOptions: createOptions(['meta', 'google', 'linkedin']),
  gridClassName: 'grid gap-4 md:grid-cols-2 xl:grid-cols-3',
  records: [
    {
      id: 'ad-1',
      name: 'Emergency Cooling Reel',
      subtitle: 'Short-form service urgency creative.',
      category: 'meta',
      metric: 'CTR 5.1%',
      accent: '#be185d',
      badge: { label: 'active', variant: 'success' },
      tags: ['Video', 'Retargeting'],
      meta: [
        { label: 'Spend', value: '$1,280' },
        { label: 'Owner', value: 'Maya C.' },
      ],
    },
    {
      id: 'ad-2',
      name: 'Commercial Retrofit Search',
      subtitle: 'High-intent paid search unit.',
      category: 'google',
      metric: 'CPL $96',
      accent: '#1d4ed8',
      badge: { label: 'active', variant: 'info' },
      tags: ['Search', 'B2B'],
      meta: [
        { label: 'Spend', value: '$2,740' },
        { label: 'Owner', value: 'Ryan N.' },
      ],
    },
    {
      id: 'ad-3',
      name: 'Facility Checklist Carousel',
      subtitle: 'LinkedIn awareness sequence for operations teams.',
      category: 'linkedin',
      metric: 'CTR 2.7%',
      accent: '#0f766e',
      badge: { label: 'testing', variant: 'warning' },
      tags: ['Carousel', 'Awareness'],
      meta: [
        { label: 'Spend', value: '$840' },
        { label: 'Owner', value: 'Sam H.' },
      ],
    },
  ],
};

export const CHART_OF_ACCOUNTS_CONFIG: RecordIndexConfig = {
  eyebrow: 'Accounting',
  title: 'Chart of Accounts',
  description: 'Ledger account records grouped for reporting and reconciliation.',
  searchPlaceholder: 'Search account codes, account names, and type',
  filterLabel: 'Account Type',
  emptyMessage: 'No accounts found for this filter.',
  filterOptions: createOptions(['asset', 'liability', 'revenue']),
  gridClassName: 'grid gap-4 md:grid-cols-2',
  records: [
    {
      id: 'coa-1',
      name: '1000 • Operating Cash',
      subtitle: 'Primary checking and settlement account group.',
      category: 'asset',
      metric: '$287,412',
      accent: '#0f766e',
      badge: { label: 'asset', variant: 'success' },
      tags: ['Banking'],
      meta: [
        { label: 'Subaccounts', value: '3' },
        { label: 'Last rec', value: 'May 27' },
      ],
    },
    {
      id: 'coa-2',
      name: '2100 • Accounts Payable',
      subtitle: 'Outstanding vendor obligations and payment queue.',
      category: 'liability',
      metric: '$44,900',
      accent: '#1d4ed8',
      badge: { label: 'liability', variant: 'info' },
      tags: ['Vendors'],
      meta: [
        { label: 'Open bills', value: '16' },
        { label: 'Owner', value: 'Accounting' },
      ],
    },
    {
      id: 'coa-3',
      name: '4100 • Service Revenue',
      subtitle: 'Recognized income from operational delivery.',
      category: 'revenue',
      metric: '$1.38M YTD',
      accent: '#7c3aed',
      badge: { label: 'revenue', variant: 'outline' },
      tags: ['P&L'],
      meta: [
        { label: 'Growth', value: '+12%' },
        { label: 'Report line', value: 'Topline' },
      ],
    },
  ],
};

export const BANK_CARDS_CONFIG: RecordIndexConfig = {
  eyebrow: 'Banking',
  title: 'Cards',
  description: 'Issued card records, limits, and activity stage.',
  hideToolbar: true,
  searchPlaceholder: 'Search card labels, owners, and limits',
  filterLabel: 'Card Type',
  emptyMessage: 'No cards match this filter.',
  filterOptions: createOptions(['virtual', 'physical']),
  gridClassName: 'grid gap-4 md:grid-cols-2',
  records: [
    {
      id: 'card-1',
      name: 'Ops Fuel Card • **** 1822',
      subtitle: 'Primary card for field fuel and transport.',
      category: 'physical',
      metric: '$1,980 / $5,000',
      accent: '#0f766e',
      badge: { label: 'active', variant: 'success' },
      tags: ['Crew A'],
      meta: [
        { label: 'Owner', value: 'Nina T.' },
        { label: 'Cycle', value: 'Monthly' },
      ],
    },
    {
      id: 'card-2',
      name: 'Ads Spend Virtual • **** 7341',
      subtitle: 'Dedicated media buying budget card.',
      category: 'virtual',
      metric: '$3,420 / $6,000',
      accent: '#be185d',
      badge: { label: 'active', variant: 'info' },
      tags: ['Marketing'],
      meta: [
        { label: 'Owner', value: 'Maya C.' },
        { label: 'Channel', value: 'Meta + Google' },
      ],
    },
    {
      id: 'card-3',
      name: 'Emergency Purchases • **** 5503',
      subtitle: 'On-demand materials and urgent replacement parts.',
      category: 'physical',
      metric: '$640 / $2,500',
      accent: '#1d4ed8',
      badge: { label: 'watch', variant: 'warning' },
      tags: ['Emergency'],
      meta: [
        { label: 'Owner', value: 'Dispatch' },
        { label: 'Alerts', value: 'Threshold 80%' },
      ],
    },
  ],
};

export const BANK_ACCOUNTS_CONFIG: RecordIndexConfig = {
  eyebrow: 'Banking',
  title: 'Bank Accounts',
  description: 'Connected account records with cash and reconciliation state.',
  hideToolbar: true,
  searchPlaceholder: 'Search bank accounts, institutions, and owner',
  filterLabel: 'Account Type',
  emptyMessage: 'No bank accounts found for this filter.',
  filterOptions: createOptions(['checking', 'savings', 'credit']),
  gridClassName: 'grid gap-4 md:grid-cols-2',
  records: [
    {
      id: 'acct-1',
      name: 'Operating Checking • Chase',
      subtitle: 'Primary revenue and payroll clearing account.',
      category: 'checking',
      metric: '$187,402',
      accent: '#0f766e',
      badge: { label: 'reconciled', variant: 'success' },
      tags: ['Primary'],
      meta: [
        { label: 'Last sync', value: '5 min ago' },
        { label: 'Owner', value: 'Accounting' },
      ],
    },
    {
      id: 'acct-2',
      name: 'Reserve Savings • Chase',
      subtitle: 'Emergency reserve and capex buffer.',
      category: 'savings',
      metric: '$92,000',
      accent: '#1d4ed8',
      badge: { label: 'stable', variant: 'info' },
      tags: ['Reserve'],
      meta: [
        { label: 'Last transfer', value: 'May 24' },
        { label: 'APR', value: '3.8%' },
      ],
    },
    {
      id: 'acct-3',
      name: 'Corporate Card Hub • Amex',
      subtitle: 'Consolidated credit account for card fleet.',
      category: 'credit',
      metric: '$14,280 due',
      accent: '#7c2d12',
      badge: { label: 'due soon', variant: 'warning' },
      tags: ['Credit'],
      meta: [
        { label: 'Due date', value: 'Jun 5' },
        { label: 'Cards linked', value: '6' },
      ],
    },
  ],
};